---
development:
  cloud_name: dqbglau6a
  api_key: '751952385683674'
  api_secret: trAzMu9CcxAeMqezphigD40mLkA
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dqbglau6a
  api_key: '751952385683674'
  api_secret: trAzMu9CcxAeMqezphigD40mLkA
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dqbglau6a
  api_key: '751952385683674'
  api_secret: trAzMu9CcxAeMqezphigD40mLkA
  enhance_image_tag: true
  static_file_support: false
